[package]
name = "axum-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "axum-server"
path = "axum-server/main.rs"

[dependencies]
axum = "0.5.15"
tokio = { version = "1.20.1", features = ["full"] }
serde = { version = "1.0.143", features = ["derive"] }